/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 ./public/mountain/scene.gltf --keepnames --keepgroups --types
Author: James Lucas (https://sketchfab.com/jameslucas)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/snowy-mountain-09ed3babc1784b9a8a40b62d4f765f66
Title: Snowy Mountain
*/

import { useGLTF } from '@react-three/drei'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'
import { useFrame } from '@react-three/fiber'
import { useRef } from 'react'

type GLTFResult = GLTF & {
	nodes: {
		Object_2: THREE.Mesh
		Object_3: THREE.Mesh
		Object_4: THREE.Mesh
		Object_5: THREE.Mesh
		Object_6: THREE.Mesh
		Object_7: THREE.Mesh
		Object_8: THREE.Mesh
		Object_9: THREE.Mesh
	}
	materials: {
		blinn1SG: THREE.MeshStandardMaterial
	}
}

export default function Mountain(props: JSX.IntrinsicElements['group']) {
	const { nodes, materials } = useGLTF('mountain/scene.glb') as GLTFResult

	const ref = useRef<THREE.Group | null>(null)

	useFrame((_, delta) => {
		if (ref.current) {
			ref.current.rotation.y = ref.current.rotation.y += delta / 3;
		}
	});


	return (
		<group {...props} dispose={null} scale={[0.005, 0.005, 0.005]} ref={ref}>
			<group name="Sketchfab_Scene">
				<group name="Sketchfab_model" position={[0, -139.13, 140.84]} rotation={[-Math.PI, 0, 0]}>
					<group name="SnowyMountainTextureobjcleanergles">
						<mesh name="Object_2" geometry={nodes.Object_2.geometry} material={materials.blinn1SG} />
						<mesh name="Object_3" geometry={nodes.Object_3.geometry} material={materials.blinn1SG} />
						<mesh name="Object_4" geometry={nodes.Object_4.geometry} material={materials.blinn1SG} />
						<mesh name="Object_5" geometry={nodes.Object_5.geometry} material={materials.blinn1SG} />
						<mesh name="Object_6" geometry={nodes.Object_6.geometry} material={materials.blinn1SG} />
						<mesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.blinn1SG} />
						<mesh name="Object_8" geometry={nodes.Object_8.geometry} material={materials.blinn1SG} />
						<mesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.blinn1SG} />
					</group>
				</group>
			</group>
		</group>
	)
}

useGLTF.preload('mountain/scene.glb')
